<Project>
  <PropertyGroup>
      <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>


<!--
                                              ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                                              █████ ▀██ ██ ▄▄▄█▄▄ ▄▄███▄▄▄ ████ ▄▄ ██
                                              █▀▀██ █ █ ██ ▄▄▄███ ██████▀▄██▀▀█ ▀▄ ██
                                              █▄▄██ ██▄ ██ ▀▀▀███ █████ ████▄▄█ ▀▀ ██
                                              ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
  -->
  <ItemGroup Label="Package versions for .NET 7.0"
    Condition=" ('$(TargetFrameworkIdentifier)' == '.NETCoreApp' And $([MSBuild]::VersionEquals($(TargetFrameworkVersion), '7.0'))) ">
    
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi"                                        Version="7.0.5"   />
    <PackageVersion Include="Swashbuckle.AspNetCore"                                              Version="6.4.0"   />
    <PackageVersion Include="Serilog.AspNetCore"                                                  Version="7.0.0"   />

    <!-- Microsoft -->
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection"                            Version="7.0.0"   />

  </ItemGroup>

<!--
                                              ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                                              █████ ▀██ ██ ▄▄▄█▄▄ ▄▄███ ▄▄ ████ ▄▄ ██
                                              █▀▀██ █ █ ██ ▄▄▄███ █████ ▀▀ █▀▀█ ▀▄ ██
                                              █▄▄██ ██▄ ██ ▀▀▀███ █████ ▀▀ █▄▄█ ▀▀ ██
                                              ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
  -->
  <ItemGroup Label="Package versions for .NET 8.0"
    Condition=" ('$(TargetFrameworkIdentifier)' == '.NETCoreApp' And $([MSBuild]::VersionEquals($(TargetFrameworkVersion), '8.0'))) ">
    
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi"                                        Version="8.0.6"   />
    <PackageVersion Include="Swashbuckle.AspNetCore"                                              Version="6.4.0"   />
    <PackageVersion Include="Serilog.AspNetCore"                                                  Version="9.0.0"   />

  </ItemGroup>

<!--
                                              ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                                              █████ ▀██ ██ ▄▄▄█▄▄ ▄▄███▀▄▄▀████ ▄▄ ██
                                              █▀▀██ █ █ ██ ▄▄▄███ █████▄▀▀ █▀▀█ ▀▄ ██
                                              █▄▄██ ██▄ ██ ▀▀▀███ ██████▀▀▄█▄▄█ ▀▀ ██
                                              ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
  -->
  <ItemGroup Label="Package versions for .NET 9.0"
    Condition=" ('$(TargetFrameworkIdentifier)' == '.NETCoreApp' And $([MSBuild]::VersionEquals($(TargetFrameworkVersion), '9.0'))) ">
    
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi"                                        Version="9.0.6"   />
    <PackageVersion Include="Swashbuckle.AspNetCore"                                              Version="6.4.0"   />
    <PackageVersion Include="Serilog.AspNetCore"                                                  Version="9.0.0"   />

  </ItemGroup>
</Project>