#!/bin/bash

declare -A commands=(
  ['Api']=Api
  ['Api-Binlog']=Api-Binlog
  ['run-docker']=run-docker
  ['stop-docker']=stop-docker
  ['build-docker']=build-docker
);

selectedCMD=$1

if [[ $# -gt 0 && ${commands[$selectedCMD]} ]]; then
    shift
    if [[ ${commands[$selectedCMD]} ]]; then

      if [[ $selectedCMD == 'Api' ]]; then
        # Certain Condition
        isWatch=false
        isBuild=false

        if [[ $1 == 'watch' ]]; then
          shift
          isWatch=true
        fi
        if [[ $1 == 'build' ]]; then
          shift
          isBuild=true
        fi

        if [[ $isWatch == true ]];then
          ( cd ./App-Api && dotnet watch run "$@" )
        elif [[ $isBuild == true ]];then
          ( cd ./App-Api && dotnet build "$@" )
        else
          ( cd ./App-Api && dotnet run "$@" )
        fi
        
      fi

      if [[ $selectedCMD == 'Api-Binlog' ]]; then
        ( cd ./App-Api && dotnet build -bl:output.binlog "$@" )
      fi

      if [[ $selectedCMD == 'build-docker' ]]; then
        docker build -f docker/dockerfile -t dotnet-web-api:latest . --progress=plain --network=host
      fi

      if [[ $selectedCMD == 'run-docker' ]]; then
        # docker build -f docker/dockerfile -t dotnet-web-api:latest . --progress=plain --network=host
        docker-compose -f docker/docker-compose.yml up -d
      fi

      if [[ $selectedCMD == 'stop-docker' ]]; then
        docker-compose -f docker/docker-compose.yml down
      fi

    else
      echo ""
      echo "unknown commands"
      echo "try one of these -> ${commands[@]}"
      echo ""
    fi
    
else
  echo ""
  echo "unknown command"
  echo "try one of these -> ${commands[@]}"
  echo "example: ./run ${commands[Api]} "
  echo ""

fi

