name: Test & Build for any problem before PR

on:
  # push:
  #   branches:
  #     - update
  pull_request:
    branches:
      - development

jobs:
  test-build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      # Setup .NET SDK 7.0
      - name: Setup .NET SDK 7.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'

      # Setup .NET SDK 8.0
      - name: Setup .NET SDK 8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # Setup .NET SDK 9.0
      - name: Setup .NET SDK 9.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Move Position To WebApi Application
        run: |
          cd ./App-Api

      - name: Restore and Build for .NET SDK 7.0
        run: |
          dotnet build
      # dotnet test --no-build

      - name: Restore and Build for .NET SDK 8.0
        run: |
          dotnet build -p:NetCoreTargetFramework=net8.0
      # dotnet test -p:NetCoreTargetFramework=net8.0 --no-build

      - name: Restore and Build for .NET SDK 9.0
        run: |
          dotnet build -p:NetCoreTargetFramework=net9.0

  test-build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      # Setup .NET SDK 7.0
      - name: Setup .NET SDK 7.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'

      # Setup .NET SDK 8.0
      - name: Setup .NET SDK 8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # Setup .NET SDK 9.0
      - name: Setup .NET SDK 9.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Move Position To WebApi Application
        run: |
          cd App-Api

      - name: Restore and Build for .NET SDK 7.0
        run: |
          dotnet build
      # dotnet test --no-build

      - name: Restore and Build for .NET SDK 8.0
        run: |
          dotnet build -p:NetCoreTargetFramework=net8.0
      # dotnet test -p:NetCoreTargetFramework=net8.0 --no-build

      - name: Restore and Build for .NET SDK 9.0
        run: |
          dotnet build -p:NetCoreTargetFramework=net9.0